{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "084e1e51-4974-4de7-9b20-ebd0db05d60c",
   "metadata": {},
   "outputs": [],
   "source": [
    "# -*- coding: utf-8 -*-\n",
    "\"\"\"\n",
    "DeepSeek-OCR 批量版 (autodl 服务器专用)\n",
    "会自动遍历 /root/fulltext 下所有 PDF，输出到 /root/markdown\n",
    "\"\"\"\n",
    "\n",
    "import os, glob, io, re\n",
    "import fitz\n",
    "import img2pdf\n",
    "import numpy as np\n",
    "from PIL import Image, ImageDraw, ImageFont\n",
    "from concurrent.futures import ThreadPoolExecutor\n",
    "from tqdm import tqdm\n",
    "import torch\n",
    "from config import (\n",
    "    INPUT_PATH, OUTPUT_PATH, MODEL_PATH, PROMPT,\n",
    "    SKIP_REPEAT, MAX_CONCURRENCY, NUM_WORKERS, CROP_MODE\n",
    ")\n",
    "from deepseek_ocr import DeepseekOCRForCausalLM\n",
    "from vllm.model_executor.models.registry import ModelRegistry\n",
    "from vllm import LLM, SamplingParams\n",
    "from process.ngram_norepeat import NoRepeatNGramLogitsProcessor\n",
    "from process.image_process import DeepseekOCRProcessor\n",
    "\n",
    "# ========== 初始化 ==========\n",
    "os.environ['VLLM_USE_V1'] = '0'\n",
    "os.environ[\"CUDA_VISIBLE_DEVICES\"] = '0'\n",
    "os.makedirs(OUTPUT_PATH, exist_ok=True)\n",
    "os.makedirs(f'{OUTPUT_PATH}/images', exist_ok=True)\n",
    "\n",
    "ModelRegistry.register_model(\"DeepseekOCRForCausalLM\", DeepseekOCRForCausalLM)\n",
    "\n",
    "llm = LLM(\n",
    "    model=MODEL_PATH,\n",
    "    hf_overrides={\"architectures\": [\"DeepseekOCRForCausalLM\"]},\n",
    "    block_size=256,\n",
    "    enforce_eager=False,\n",
    "    trust_remote_code=True,\n",
    "    max_model_len=8192,\n",
    "    swap_space=0,\n",
    "    max_num_seqs=MAX_CONCURRENCY,\n",
    "    tensor_parallel_size=1,\n",
    "    gpu_memory_utilization=0.9,\n",
    "    disable_mm_preprocessor_cache=True\n",
    ")\n",
    "\n",
    "logits_processors = [\n",
    "    NoRepeatNGramLogitsProcessor(\n",
    "        ngram_size=20, window_size=50,\n",
    "        whitelist_token_ids={128821, 128822}\n",
    "    )\n",
    "]\n",
    "\n",
    "sampling_params = SamplingParams(\n",
    "    temperature=0.0,\n",
    "    max_tokens=8192,\n",
    "    logits_processors=logits_processors,\n",
    "    skip_special_tokens=False,\n",
    "    include_stop_str_in_output=True,\n",
    ")\n",
    "\n",
    "# ========== 基础工具函数 ==========\n",
    "def pdf_to_images_high_quality(pdf_path, dpi=144):\n",
    "    \"\"\"将 PDF 渲染为高质量图片列表\"\"\"\n",
    "    images = []\n",
    "    pdf_document = fitz.open(pdf_path)\n",
    "    zoom = dpi / 72.0\n",
    "    matrix = fitz.Matrix(zoom, zoom)\n",
    "    for page_num in range(pdf_document.page_count):\n",
    "        page = pdf_document[page_num]\n",
    "        pixmap = page.get_pixmap(matrix=matrix, alpha=False)\n",
    "        Image.MAX_IMAGE_PIXELS = None\n",
    "        img = Image.open(io.BytesIO(pixmap.tobytes(\"png\")))\n",
    "        images.append(img)\n",
    "    pdf_document.close()\n",
    "    return images\n",
    "\n",
    "def pil_to_pdf_img2pdf(pil_images, output_path):\n",
    "    \"\"\"将标注后的 PIL 图像合并为 PDF\"\"\"\n",
    "    if not pil_images:\n",
    "        return\n",
    "    imgs_bytes = []\n",
    "    for img in pil_images:\n",
    "        if img.mode != 'RGB':\n",
    "            img = img.convert('RGB')\n",
    "        buf = io.BytesIO()\n",
    "        img.save(buf, format='JPEG', quality=95)\n",
    "        imgs_bytes.append(buf.getvalue())\n",
    "    pdf_bytes = img2pdf.convert(imgs_bytes)\n",
    "    with open(output_path, \"wb\") as f:\n",
    "        f.write(pdf_bytes)\n",
    "\n",
    "def re_match(text):\n",
    "    pattern = r'(<\\|ref\\|>(.*?)<\\|/ref\\|><\\|det\\|>(.*?)<\\|/det\\|>)'\n",
    "    matches = re.findall(pattern, text, re.DOTALL)\n",
    "    images, others = [], []\n",
    "    for m in matches:\n",
    "        if '<|ref|>image<|/ref|>' in m[0]:\n",
    "            images.append(m[0])\n",
    "        else:\n",
    "            others.append(m[0])\n",
    "    return matches, images, others\n",
    "\n",
    "def extract_coordinates_and_label(ref_text, w, h):\n",
    "    try:\n",
    "        label = ref_text[1]\n",
    "        coords = eval(ref_text[2])\n",
    "        return (label, coords)\n",
    "    except Exception:\n",
    "        return None\n",
    "\n",
    "def draw_bounding_boxes(image, refs, jdx):\n",
    "    \"\"\"在图片上绘制检测框\"\"\"\n",
    "    w, h = image.size\n",
    "    img_draw = image.copy()\n",
    "    overlay = Image.new('RGBA', img_draw.size, (0, 0, 0, 0))\n",
    "    draw = ImageDraw.Draw(img_draw)\n",
    "    draw2 = ImageDraw.Draw(overlay)\n",
    "    font = ImageFont.load_default()\n",
    "    img_idx = 0\n",
    "    for ref in refs:\n",
    "        result = extract_coordinates_and_label(ref, w, h)\n",
    "        if not result:\n",
    "            continue\n",
    "        label, points_list = result\n",
    "        color = (np.random.randint(0,200), np.random.randint(0,200), np.random.randint(0,255))\n",
    "        color_a = color + (20,)\n",
    "        for points in points_list:\n",
    "            x1,y1,x2,y2 = points\n",
    "            x1, y1 = int(x1/999*w), int(y1/999*h)\n",
    "            x2, y2 = int(x2/999*w), int(y2/999*h)\n",
    "            if label == 'image':\n",
    "                cropped = image.crop((x1,y1,x2,y2))\n",
    "                cropped.save(f\"{OUTPUT_PATH}/images/{jdx}_{img_idx}.jpg\")\n",
    "                img_idx += 1\n",
    "            draw.rectangle([x1,y1,x2,y2], outline=color, width=2)\n",
    "            draw2.rectangle([x1,y1,x2,y2], fill=color_a, outline=(0,0,0,0), width=1)\n",
    "            draw.text((x1, max(0, y1-15)), label, font=font, fill=color)\n",
    "    img_draw.paste(overlay, (0,0), overlay)\n",
    "    return img_draw\n",
    "\n",
    "def process_single_image(image, prompt):\n",
    "    return {\n",
    "        \"prompt\": prompt,\n",
    "        \"multi_modal_data\": {\"image\": DeepseekOCRProcessor().tokenize_with_images(\n",
    "            images=[image], bos=True, eos=True, cropping=CROP_MODE)},\n",
    "    }\n",
    "\n",
    "# ========== 批量处理主流程 ==========\n",
    "def process_pdf(pdf_path):\n",
    "    base = os.path.splitext(os.path.basename(pdf_path))[0]\n",
    "    print(f\"\\n[INFO] Processing: {pdf_path}\")\n",
    "\n",
    "    try:\n",
    "        images = pdf_to_images_high_quality(pdf_path)\n",
    "    except Exception as e:\n",
    "        print(f\"❌ Failed to open PDF: {e}\")\n",
    "        return\n",
    "\n",
    "    with ThreadPoolExecutor(max_workers=NUM_WORKERS) as ex:\n",
    "        batch_inputs = list(tqdm(ex.map(lambda img: process_single_image(img, PROMPT), images),\n",
    "                                 total=len(images), desc=\"Pre-processing\"))\n",
    "\n",
    "    outputs_list = llm.generate(batch_inputs, sampling_params=sampling_params)\n",
    "    mmd_det_path = os.path.join(OUTPUT_PATH, f\"{base}_det.mmd\")\n",
    "    mmd_path = os.path.join(OUTPUT_PATH, f\"{base}.mmd\")\n",
    "    pdf_out_path = os.path.join(OUTPUT_PATH, f\"{base}_layouts.pdf\")\n",
    "\n",
    "    contents_det, contents = '', ''\n",
    "    draw_images, jdx = [], 0\n",
    "\n",
    "    for output, img in zip(outputs_list, images):\n",
    "        text = output.outputs[0].text\n",
    "        text = text.replace('<｜end▁of▁sentence｜>', '')\n",
    "        if not text and SKIP_REPEAT:\n",
    "            continue\n",
    "\n",
    "        page_sep = \"\\n<--- Page Split --->\\n\"\n",
    "        contents_det += text + page_sep\n",
    "        matches_ref, matches_images, matches_other = re_match(text)\n",
    "        result_img = draw_bounding_boxes(img, matches_ref, jdx)\n",
    "        draw_images.append(result_img)\n",
    "\n",
    "        for idx, m_img in enumerate(matches_images):\n",
    "            text = text.replace(m_img, f'![](images/{jdx}_{idx}.jpg)\\n')\n",
    "        for m_other in matches_other:\n",
    "            text = text.replace(m_other, '')\n",
    "        text = text.replace('\\\\coloneqq', ':=').replace('\\\\eqqcolon', '=:')\n",
    "        contents += text + page_sep\n",
    "        jdx += 1\n",
    "\n",
    "    with open(mmd_det_path, 'w', encoding='utf-8') as f: f.write(contents_det)\n",
    "    with open(mmd_path, 'w', encoding='utf-8') as f: f.write(contents)\n",
    "    pil_to_pdf_img2pdf(draw_images, pdf_out_path)\n",
    "    print(f\"✅ Done: {base}\")\n",
    "\n",
    "# ========== 主入口 ==========\n",
    "def find_pdfs(path):\n",
    "    return sorted(glob.glob(os.path.join(path, \"**/*.pdf\"), recursive=True))\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    pdf_files = find_pdfs(INPUT_PATH)\n",
    "    print(f\"[INFO] Found {len(pdf_files)} PDFs under {INPUT_PATH}\")\n",
    "    for pdf in pdf_files:\n",
    "        process_pdf(pdf)\n",
    "\n",
    "    # 自动打包结果方便下载\n",
    "    os.system(f\"cd {OUTPUT_PATH} && zip -r markdown_results.zip . && cd -\")\n",
    "    print(f\"\\n🎉 All done! Results saved to: {OUTPUT_PATH}/markdown_results.zip\")\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
